spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spaces?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: docker

application:
  name: spaces-users-service

server:
  port: 8000